// This file is the central source for all icons used in the application.
// By centralizing icon exports, we can easily manage, update, or replace them in the future.
// Этот файл является центральным источником для всех иконок, используемых в приложении.
// Централизация экспорта иконок позволяет легко управлять, обновлять или заменять их в будущем.

export {
  Bell,
  Settings,
  Search,
  Pencil,
  Tags,
  Image as ImageIcon, // Renamed to avoid conflict with Next/Image // Переименовано, чтобы избежать конфликта с Next/Image
  Star,
  Users,
  DollarSign,
  Trash2,
  PlusCircle,
  UserCog,
  Check,
  ShieldCheck,
  ShieldX,
  Award,
  BookCheck,
  Gem,
  Loader2,
  MessageSquare,
  User,
  Calendar as CalendarIcon,
  ArrowLeft,
  Edit,
  Camera,
  History,
  MapPin,
  Phone,
  Mail,
  KeyRound,
  Send,
  XCircle,
  Clock,
  CheckCircle,
  Eye,
  MessageCircle as MessageCircleIcon,
  Cookie,
  Copy,
  Send as SendIcon,
  Facebook,
  Twitter,
  Instagram,
  Linkedin,
  GitCompare,
  ChefHat,
  Music,
  Palette,
  Mic,
  Car,
  Film,
  Flower2,
  Smile,
  Brush,
  Utensils,
  MicVocal,
  BookOpen,
  Wallet,
  Heart,
  X,
  Upload,
  Save,
  Menu,
  ChevronDown,
  ChevronRight,
  LogOut,
  ShieldQuestion,
  Briefcase,
  List,
  Map as MapIcon,
  BadgeCheck,
  Type as TypeIcon,
  HelpCircle,
  BarChart,
  ShieldAlert,
  Handshake,
  AlertCircle,
} from "lucide-react";
